import { create } from "zustand"
import type { TravelGuide } from "../../types/content-types"

const DEFAULT: TravelGuide[] = [
  { id: "1", name: "丽江古城热门打卡之旅", tags: ["热门", "摄影"], duration: "3小时", difficulty: "中等", stops: 6, distance: "2.4km", spotNames: ["大水车", "祈福桥", "四方街", "万古楼"], description: "带你一次走完古城最具代表性的六处热门地标，从大水车到万古楼，串起古城的历史脉络与烟火气息，适合初次来丽江的游客。", cover: "https://images.unsplash.com/photo-1663609968423-657ff4f0dd5a?auto=format&fit=crop&w=1200&q=70", hasVideo: true, videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4", videoCoverUrl: "https://images.unsplash.com/photo-1663609968423-657ff4f0dd5a?auto=format&fit=crop&w=800&q=70", videoDuration: "03:45", contentBlocks: [{ id: "cb1", type: "text", text: "丽江古城位于云南省丽江市古城区，是中国历史文化名城中保存最为完整的古城之一。古城始建于宋末元初，距今已有800多年的历史。\n\n漫步在古城的青石板路上，两侧是古朴的纳西族民居，潺潺的水渠穿城而过，构成了一幅「小桥流水人家」的诗意画卷。" }], spots: [{ id: "s1", name: "大水车", desc: "古城地标入口", top: "10%", left: "52%" }, { id: "s2", name: "玉河广场", desc: "观景休憩点", top: "24%", left: "40%" }, { id: "s3", name: "祈福桥", desc: "纳西风情桥", top: "38%", left: "60%" }, { id: "s4", name: "四方街", desc: "古城核心商圈", top: "54%", left: "46%" }, { id: "s5", name: "木府入口", desc: "土司府邸", top: "72%", left: "32%" }, { id: "s6", name: "万古楼", desc: "古城至高点", top: "86%", left: "58%" }] },
  { id: "2", name: "纳西王府深度研学路线", tags: ["深度", "文化"], duration: "4小时", difficulty: "较难", stops: 4, distance: "1.8km", spotNames: ["忠义坊", "木家院", "议事厅", "后花园"], description: "走进明清木氏土司府邸，由资深讲解员带领，系统了解纳西文化与木府六百年兴衰，适合亲子研学与深度文化爱好者。", cover: "https://images.unsplash.com/photo-1683825093397-5bbc64e496e6?auto=format&fit=crop&w=1200&q=70", spots: [{ id: "s1", name: "忠义坊", desc: "木府正门牌坊", top: "14%", left: "50%" }, { id: "s2", name: "议事厅", desc: "土司议政之所", top: "38%", left: "38%" }, { id: "s3", name: "木家院", desc: "家族内宅", top: "62%", left: "56%" }, { id: "s4", name: "后花园", desc: "园林景观", top: "86%", left: "44%" }] },
  { id: "3", name: "黑龙潭雪山倒影漫步", tags: ["摄影", "热门"], duration: "2小时", difficulty: "简单", stops: 5, distance: "1.5km", spotNames: ["五凤楼", "解脱林", "万寿亭", "龙神祠"], description: "沿黑龙潭湖畔漫步，远眺玉龙雪山在湖面的倒影，是拍照与静心散步的绝佳路线。晴天建议上午 9 点前到达。", cover: "https://images.unsplash.com/photo-1672843458713-7e225a484ae1?auto=format&fit=crop&w=1200&q=70", spots: [{ id: "s1", name: "黑龙潭正门", desc: "入口", top: "8%", left: "50%" }, { id: "s2", name: "五凤楼", desc: "明代古建", top: "28%", left: "40%" }, { id: "s3", name: "解脱林", desc: "古树群", top: "48%", left: "58%" }, { id: "s4", name: "万寿亭", desc: "湖心亭观景", top: "68%", left: "42%" }, { id: "s5", name: "龙神祠", desc: "求福圣地", top: "88%", left: "54%" }] },
  { id: "4", name: "寻味古城·非遗美食品鉴", tags: ["美食", "热门"], duration: "5小时", difficulty: "较难", stops: 8, distance: "3.2km", spotNames: ["忠义市场", "鸡豆凉粉", "丽江粑粑", "酥油茶"], description: "跟着吃货达人走访古城八大必吃小店，涵盖纳西正餐、传统小吃与茶饮，带你从早到晚吃遍古城。", cover: "https://images.unsplash.com/photo-1552526881-5517a57c17ae?auto=format&fit=crop&w=1200&q=70", spots: [{ id: "s1", name: "忠义市场", desc: "食材集散地", top: "10%", left: "48%" }, { id: "s2", name: "阿妈意饭店", desc: "纳西火锅", top: "22%", left: "60%" }, { id: "s3", name: "鸡豆凉粉", desc: "经典小吃", top: "34%", left: "36%" }, { id: "s4", name: "丽江粑粑", desc: "老字号", top: "46%", left: "56%" }, { id: "s5", name: "五一街茶馆", desc: "下午茶", top: "58%", left: "42%" }, { id: "s6", name: "酥油茶坊", desc: "纳西传统", top: "70%", left: "60%" }, { id: "s7", name: "鲜花饼店", desc: "伴手礼", top: "82%", left: "38%" }, { id: "s8", name: "酒吧一条街", desc: "夜宵收尾", top: "92%", left: "52%" }] },
]

type State = { guides: TravelGuide[]; addGuide: (item: TravelGuide) => void; updateGuide: (id: string, fields: Partial<TravelGuide>) => void; deleteGuide: (id: string) => void }

export const useContentGuideStore = create<State>((set) => ({
  guides: DEFAULT,
  addGuide: (item) => set((s) => ({ guides: [...s.guides, item] })),
  updateGuide: (id, fields) => set((s) => ({ guides: s.guides.map((g) => g.id === id ? { ...g, ...fields } : g) })),
  deleteGuide: (id) => set((s) => ({ guides: s.guides.filter((g) => g.id !== id) })),
}))
